# Generated by Django 5.2.9 on 2025-12-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='assunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
