# Generated by Django 5.2.9 on 2025-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disponibilidade_assunto_disponibilidade_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='nivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
