# Generated by Django 5.2.9 on 2025-12-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_disponibilidade_descricao_disponibilidade_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Aguardando Confirmação'), ('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('aluno', 'disponibilidade')},
        ),
    ]
